# -*- coding: utf-8 -*-
import sys
import os

myDir = os.getcwd()
sys.path.append(myDir)

from src.controller.GenresController import GenresController
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenresUI(object):
    def __init__(self, user):
        self.user = user
        self.main_controller = GenresController(self,user)

    def setupUi(self, GenresUI):
        GenresUI.setObjectName("GenresUI")
        GenresUI.resize(600, 530)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/images/libro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GenresUI.setWindowIcon(icon)
        GenresUI.setStyleSheet("background-color:#107acc;")
        self.label = QtWidgets.QLabel(GenresUI)
        self.label.setGeometry(QtCore.QRect(130, 50, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(GenresUI)
        self.frame.setGeometry(QtCore.QRect(210, 230, 181, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(50, 140, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(50, 170, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(50, 200, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        
        self.enterGenreLine = QtWidgets.QLineEdit(GenresUI)
        self.enterGenreLine.setGeometry(QtCore.QRect(220, 120, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.enterGenreLine.setFont(font)
        self.enterGenreLine.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.enterGenreLine.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.enterGenreLine.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enterGenreLine.setObjectName("enterGenreLine")
        self.startBtn = QtWidgets.QPushButton(GenresUI)
        self.startBtn.setGeometry(QtCore.QRect(270, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet("border:1px solid white;\n"
"border-radius:4px;\n"
"color:white;")
        self.startBtn.setObjectName("startBtn")
        self.label_10 = QtWidgets.QLabel(GenresUI)
        self.label_10.setGeometry(QtCore.QRect(30, 160, 141, 111))
        self.label_10.setStyleSheet("border-radius:10px;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("src/images/adventure.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(GenresUI)
        self.label_11.setGeometry(QtCore.QRect(30, 310, 141, 111))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("src/images/sci-fi.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(GenresUI)
        self.label_12.setGeometry(QtCore.QRect(430, 160, 141, 111))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("src/images/horror.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(GenresUI)
        self.label_13.setGeometry(QtCore.QRect(430, 310, 141, 111))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("src/images/romance.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")

        self.retranslateUi(GenresUI)
        QtCore.QMetaObject.connectSlotsByName(GenresUI)


        # ------------- ACTIONS

        self.startBtn.clicked.connect(lambda:self.main_controller.chargeGenre(GenresUI))

    def retranslateUi(self, GenresUI):
        _translate = QtCore.QCoreApplication.translate
        GenresUI.setWindowTitle(_translate("GenresUI", "Genres"))
        self.label.setText(_translate("GenresUI", "Write the Theme that you want"))
        self.label_2.setText(_translate("GenresUI", "Adventure"))
        self.label_3.setText(_translate("GenresUI", "Sci-Fi"))
        self.label_4.setText(_translate("GenresUI", "Drama"))
        self.label_5.setText(_translate("GenresUI", "Fantasy"))
        self.label_6.setText(_translate("GenresUI", "Mystery"))
        self.label_7.setText(_translate("GenresUI", "Horror"))
        self.label_8.setText(_translate("GenresUI", "Historical"))
        
        self.startBtn.setText(_translate("GenresUI", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GenresUI = QtWidgets.QWidget()
    ui = Ui_GenresUI()
    ui.setupUi(GenresUI)
    GenresUI.show()
    sys.exit(app.exec_())
